[package]
name = "ninchy"
version = "0.1.0"
authors = ["Atta Zadeh <atta.h.zadeh@gmail.com>"]

[dependencies]
bytes = "0.4"
chrono = "0.4.0"
failure = "0.1.2"
futures = "0.1"
env_logger = "*"
log = "0.4"
num_cpus = "1.8.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

actix = "0.7"
actix-web = "^0.7"

diesel = { version = "1.0.0", features = ["postgres", "chrono", "r2d2"] }
dotenv = "0.9.0"

objekt = "0.1.1"