[package]
name = "ninchy"
version = "0.1.0"
authors = ["Atta Zadeh <atta.h.zadeh@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
env_logger = "*"
log = "0.4"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

actix = "0.7"
actix-web = "^0.7"

objekt = "0.1.1"